remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: A sample repo to test
description: We will make analysis on NBA datasets to gain some interesting facts